
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doogpark_development
  host: 127.0.0.1

test:
  <<: *default
  database: doogpark_test
  host: 127.0.0.1

production:
  <<: *default
  database: doogpark_production
  host: 127.0.0.1
  username: doogpark
  password: admin